# Generated by Django 5.1.6 on 2025-02-28 14:40

from django.db import migrations, models
#adding comment


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0013_survey_success_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Specify the expiration date for this survey.', null=True, verbose_name='valid until'),
        ),
    ]
