# Generated by Django 5.1.5 on 2025-03-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0014_survey_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the survey expires. Leave blank for no expiration.', null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the survey becomes available. Leave blank for immediate availability.', null=True, verbose_name='start date'),
        ),
    ]
