# Generated by Django 5.1.7 on 2025-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0015_survey_end_date_survey_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='target_responses',
            field=models.PositiveIntegerField(default=100, help_text='Target number of responses for this survey', verbose_name='target responses'),
        ),
    ]
