# Generated by Django 5.2 on 2025-04-25 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0016_survey_target_responses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='duplicate_entry',
            field=models.BooleanField(default=False, help_text='If True, users can submit multiple times. If False (default), users can only submit once.', verbose_name='multiple submissions'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('survey', 'user')},
        ),
    ]
