name: Cypress Login Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create test users
      run: |
        python manage.py shell -c "from django.contrib.auth.models import User; User.objects.filter(username='test@gmail.com').exists() or User.objects.create_user(username='test@gmail.com', email='test@gmail.com', password='test')"
        python manage.py shell -c "from django.contrib.auth.models import User; User.objects.filter(username='admintest').exists() or User.objects.create_superuser(username='admintest', email='admintest@example.com', password='admintest')"
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Run Django server and Cypress login tests
      uses: cypress-io/github-action@v5
      with:
        start: python manage.py runserver
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 120
        # Only testing the login functionality
        spec: "cypress/e2e/login.cy.js"
        
    - name: Archive test screenshots on failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        retention-days: 5 